command: ["sh", "-c", "cd frontend && npm install --include=dev && npm run build && cd .. && uvicorn app:app --host 0.0.0.0 --port ${DATABRICKS_APP_PORT:-8000}"]
env:
  - name: DATABRICKS_SQL_WAREHOUSE_ID
    value: ""
  - name: MODEL_SERVING_DBU_PRICE
    value: "0.07"
  - name: ADMIN_USERS
    value: "yan.barta@blindspot.ai"
