importexport { default } from './UsageChartPanel';
{export { default } from './UsageChartPanel';
Bar,export { default } from './UsageChartPanel';
BarChart,export { default } from './UsageChartPanel';
CartesianGrid,export { default } from './UsageChartPanel';
ResponsiveContainer,export { default } from './UsageChartPanel';
Tooltip,export { default } from './UsageChartPanel';
XAxis,export { default } from './UsageChartPanel';
YAxisexport { default } from './UsageChartPanel';
}export { default } from './UsageChartPanel';
fromexport { default } from './UsageChartPanel';
'recharts';
importexport { default } from './UsageChartPanel';
typeexport { default } from './UsageChartPanel';
{export { default } from './UsageChartPanel';
UsageRowexport { default } from './UsageChartPanel';
}export { default } from './UsageChartPanel';
fromexport { default } from './UsageChartPanel';
'../api';

typeexport { default } from './UsageChartPanel';
UsageChartPropsexport { default } from './UsageChartPanel';
=export { default } from './UsageChartPanel';
{
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
rows:export { default } from './UsageChartPanel';
UsageRow[];
};

functionexport { default } from './UsageChartPanel';
aggregateByUser(rows:export { default } from './UsageChartPanel';
UsageRow[])export { default } from './UsageChartPanel';
{
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
constexport { default } from './UsageChartPanel';
totalsexport { default } from './UsageChartPanel';
=export { default } from './UsageChartPanel';
newexport { default } from './UsageChartPanel';
Map<string,export { default } from './UsageChartPanel';
number>();
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
rows.forEach((row)export { default } from './UsageChartPanel';
=>export { default } from './UsageChartPanel';
{
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
totals.set(row.user,export { default } from './UsageChartPanel';
(totals.get(row.user)export { default } from './UsageChartPanel';
??export { default } from './UsageChartPanel';
0)export { default } from './UsageChartPanel';
+export { default } from './UsageChartPanel';
row.estimated_cost);
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
});

export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
returnexport { default } from './UsageChartPanel';
Array.from(totals.entries())
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
.map(([user,export { default } from './UsageChartPanel';
cost])export { default } from './UsageChartPanel';
=>export { default } from './UsageChartPanel';
({export { default } from './UsageChartPanel';
user,export { default } from './UsageChartPanel';
cost:export { default } from './UsageChartPanel';
Number(cost.toFixed(4))export { default } from './UsageChartPanel';
}))
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
.sort((left,export { default } from './UsageChartPanel';
right)export { default } from './UsageChartPanel';
=>export { default } from './UsageChartPanel';
right.costexport { default } from './UsageChartPanel';
-export { default } from './UsageChartPanel';
left.cost)
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
.slice(0,export { default } from './UsageChartPanel';
10);
}

exportexport { default } from './UsageChartPanel';
defaultexport { default } from './UsageChartPanel';
functionexport { default } from './UsageChartPanel';
UsageChart({export { default } from './UsageChartPanel';
rowsexport { default } from './UsageChartPanel';
}:export { default } from './UsageChartPanel';
UsageChartProps)export { default } from './UsageChartPanel';
{
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
constexport { default } from './UsageChartPanel';
chartDataexport { default } from './UsageChartPanel';
=export { default } from './UsageChartPanel';
aggregateByUser(rows);

export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
returnexport { default } from './UsageChartPanel';
(
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
<divexport { default } from './UsageChartPanel';
style={{export { default } from './UsageChartPanel';
height:export { default } from './UsageChartPanel';
320,export { default } from './UsageChartPanel';
width:export { default } from './UsageChartPanel';
'100%'export { default } from './UsageChartPanel';
}}>
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
<ResponsiveContainer>
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
<BarChartexport { default } from './UsageChartPanel';
data={chartData}export { default } from './UsageChartPanel';
layout="vertical"export { default } from './UsageChartPanel';
margin={{export { default } from './UsageChartPanel';
top:export { default } from './UsageChartPanel';
8,export { default } from './UsageChartPanel';
right:export { default } from './UsageChartPanel';
24,export { default } from './UsageChartPanel';
left:export { default } from './UsageChartPanel';
12,export { default } from './UsageChartPanel';
bottom:export { default } from './UsageChartPanel';
8export { default } from './UsageChartPanel';
}}>
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
<CartesianGridexport { default } from './UsageChartPanel';
stroke="rgba(148,export { default } from './UsageChartPanel';
163,export { default } from './UsageChartPanel';
184,export { default } from './UsageChartPanel';
0.12)"export { default } from './UsageChartPanel';
horizontal={false}export { default } from './UsageChartPanel';
/>
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
<XAxisexport { default } from './UsageChartPanel';
type="number"export { default } from './UsageChartPanel';
tick={{export { default } from './UsageChartPanel';
fill:export { default } from './UsageChartPanel';
'#94a3b8'export { default } from './UsageChartPanel';
}}export { default } from './UsageChartPanel';
axisLine={false}export { default } from './UsageChartPanel';
tickLine={false}export { default } from './UsageChartPanel';
/>
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
<YAxisexport { default } from './UsageChartPanel';
dataKey="user"export { default } from './UsageChartPanel';
type="category"export { default } from './UsageChartPanel';
width={180}export { default } from './UsageChartPanel';
tick={{export { default } from './UsageChartPanel';
fill:export { default } from './UsageChartPanel';
'#cbd5e1',export { default } from './UsageChartPanel';
fontSize:export { default } from './UsageChartPanel';
12export { default } from './UsageChartPanel';
}}export { default } from './UsageChartPanel';
axisLine={false}export { default } from './UsageChartPanel';
tickLine={false}export { default } from './UsageChartPanel';
/>
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
<Tooltip
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
cursor={{export { default } from './UsageChartPanel';
fill:export { default } from './UsageChartPanel';
'rgba(148,export { default } from './UsageChartPanel';
163,export { default } from './UsageChartPanel';
184,export { default } from './UsageChartPanel';
0.08)'export { default } from './UsageChartPanel';
}}
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
contentStyle={{
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
background:export { default } from './UsageChartPanel';
'#0f172a',
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
border:export { default } from './UsageChartPanel';
'1pxexport { default } from './UsageChartPanel';
solidexport { default } from './UsageChartPanel';
rgba(148,export { default } from './UsageChartPanel';
163,export { default } from './UsageChartPanel';
184,export { default } from './UsageChartPanel';
0.2)',
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
borderRadius:export { default } from './UsageChartPanel';
12,
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
color:export { default } from './UsageChartPanel';
'#e2e8f0',
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
}}
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
formatter={(value:export { default } from './UsageChartPanel';
number)export { default } from './UsageChartPanel';
=>export { default } from './UsageChartPanel';
[`${value.toFixed(4)}`,export { default } from './UsageChartPanel';
'Estimatedexport { default } from './UsageChartPanel';
Cost']}
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
/>
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
<Barexport { default } from './UsageChartPanel';
dataKey="cost"export { default } from './UsageChartPanel';
fill="#38bdf8"export { default } from './UsageChartPanel';
radius={[0,export { default } from './UsageChartPanel';
8,export { default } from './UsageChartPanel';
8,export { default } from './UsageChartPanel';
0]}export { default } from './UsageChartPanel';
/>
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
</BarChart>
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
</ResponsiveContainer>
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
</div>
export { default } from './UsageChartPanel';
export { default } from './UsageChartPanel';
);
}
